# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Tullia Glaeser
  de: Tullia Gläser
  it: Tullia Glaeser
  fr: Tullia Glaeser
email: firstinitial lastname AT tulane DOT edu
description:
  en: Personal Website
  de: 
  it: 
  fr:
index:
  en:
  de: de.html
  it: it.html
  fr: fr.html
feed:
  en: /feed.xml
  de: /feed-de.xml
  it: /feed-it.xml
  fr: /feed-fr.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
linkedin_username: tamglaeser
github_username:  tamglaeser
keybase_username: tullia

# Build settings
markdown: kramdown
mathjax: true

# theme: jekyll-theme-minimal
